<script setup>
/**
 * pages/index.vue – SSI Dictionary home page
 *
 * Loads dictionary.json (generated by the GitHub Action) and passes it to
 * DictionaryView. The useFetch call is isomorphic: it runs at build time
 * during `nuxt generate` (SSG) and also works client-side.
 */

const { data: dictionaryPayload, status, error } = await useFetch('/api/dictionary.json', {
  // Cache the response so repeated navigations don't re-fetch
  key: 'dictionary',
  default: () => ({ termsData: [], lastBuiltAt: null })
})

const termsData = computed(() => dictionaryPayload.value?.termsData ?? [])
const lastBuiltAt = computed(() => dictionaryPayload.value?.lastBuiltAt ?? null)

function clearHashFromUrl() {
  if (!import.meta.client) return
  const { pathname, search } = globalThis.location
  globalThis.history.replaceState(null, '', `${pathname}${search}`)
}
</script>

<template>
  <div>
    <!-- Hero -->
    <header class="ssi-hero text-center py-1">
      <h1 class="ssi-hero__title m-0">
        <button type="button" class="ssi-hero__title-button" @click="clearHashFromUrl">
          Self Sovereign Identity (SSI) Dictionary
        </button>
      </h1>
      <!-- <p class="ssi-hero__subtitle">
        Cryptographically-rooted definitions from authoritative Self-Sovereign
        Identity standards bodies — decentralized trust, no single point of
        control.
      </p> -->
      <!-- <div class="ssi-hero__badge-row">
        <span class="ssi-hero__badge">🔐 cryptography</span>
        <span class="ssi-hero__badge">🌐 decentralized trust</span>
        <span class="ssi-hero__badge">🔑 self-sovereign identity</span>
        <span class="ssi-hero__badge">📜 verifiable credentials</span>
        <span class="ssi-hero__badge">⛓ keri</span>
      </div> -->
    </header>

    <div class="container-fluid py-3 px-0">
      <!-- Loading state -->
      <div v-if="status === 'pending'" class="text-center py-5">
        <div class="spinner-border" role="status" aria-hidden="true"></div>
        <p class="mt-3 text-muted">
          <span class="term-prompt">$</span> loading dictionary&hellip;
        </p>
      </div>

      <!-- Error state -->
      <div v-else-if="error" class="alert alert-danger" role="alert">
        <strong>&gt; ERROR:</strong> Could not load dictionary.<br />
        The <code>public/data/dictionary.json</code> file is missing or empty.
        Run <code>npm run fetch-glossaries</code> locally first, then restart.
        <details class="mt-2">
          <summary>Stack trace</summary>
          <pre class="mt-1 small">{{ error }}</pre>
        </details>
      </div>

      <!-- Dictionary -->
      <DictionaryView v-else :terms-data="termsData" :last-built-at="lastBuiltAt" />
    </div>
  </div>
</template>

<style scoped>
.term-prompt {
  color: var(--clr-green);
  font-weight: 700;
  margin-right: 0.4em;
}

.ssi-hero__title-button {
  border: 0;
  background: transparent;
  padding: 0;
  color: inherit;
  font: inherit;
  cursor: pointer;
}

.ssi-hero__title-button:hover {
  text-decoration: underline;
}

.ssi-hero__title-button:focus-visible {
  outline: 2px solid currentColor;
  outline-offset: 4px;
}

.ssi-hero__title {
  font-size: 1.75rem;
}

@media (max-width: 575.98px) {
  .ssi-hero__title {
    font-size: 1.15rem;
  }
}
</style>
