<script setup>
/**
 * pages/index.vue – SSI Dictionary home page
 *
 * Loads dictionary.json (generated by the GitHub Action) and passes it to
 * DictionaryView. The useFetch call is isomorphic: it runs at build time
 * during `nuxt generate` (SSG) and also works client-side.
 */

const { data: termsData, status, error } = await useFetch('/api/dictionary.json', {
  // Cache the response so repeated navigations don't re-fetch
  key: 'dictionary',
  default: () => []
})
</script>

<template>
  <div class="container py-5">
    <header class="mb-5">
      <h1 class="display-5 fw-bold">SSI Dictionary</h1>
      <p class="lead text-muted">
        Searchable definitions from multiple Self-Sovereign Identity standards
        bodies and communities.
      </p>
    </header>

    <!-- Loading state -->
    <div v-if="status === 'pending'" class="text-center py-5">
      <div class="spinner-border text-secondary" role="status">
        <span class="visually-hidden">Loading dictionary…</span>
      </div>
      <p class="mt-3 text-muted">Loading dictionary…</p>
    </div>

    <!-- Error state -->
    <div v-else-if="error" class="alert alert-danger" role="alert">
      <strong>Could not load dictionary.</strong>
      The <code>public/data/dictionary.json</code> file is missing or empty.
      Run <code>npm run fetch-glossaries</code> locally first, then restart the dev server.
      <details class="mt-2">
        <summary>Error details</summary>
        <pre class="mt-1 small">{{ error }}</pre>
      </details>
    </div>

    <!-- Dictionary -->
    <DictionaryView v-else :terms-data="termsData" />
  </div>
</template>
